import type { Album, Tag } from "./types";

export const mockAlbums: Album[] = [
  {
    id: "1",
    name: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    image: "/placeholder.svg?height=300&width=300",
    year: 1973,
    genres: ["Progressive Rock", "Psychedelic Rock"],
    isFavorite: false,
    tags: [],
  },
  {
    id: "2",
    name: "OK Computer",
    artist: "Radiohead",
    image: "/placeholder.svg?height=300&width=300",
    year: 1997,
    genres: ["Alternative Rock", "Electronic"],
    isFavorite: false,
    tags: [],
  },
  {
    id: "3",
    name: "Kind of Blue",
    artist: "Miles Davis",
    image: "/placeholder.svg?height=300&width=300",
    year: 1959,
    genres: ["Jazz", "Cool Jazz"],
    isFavorite: false,
    tags: [],
  },
  {
    id: "4",
    name: "Nevermind",
    artist: "Nirvana",
    image: "/placeholder.svg?height=300&width=300",
    year: 1991,
    genres: ["Grunge", "Alternative Rock"],
    isFavorite: false,
    tags: [],
  },
  {
    id: "5",
    name: "Thriller",
    artist: "Michael Jackson",
    image: "/placeholder.svg?height=300&width=300",
    year: 1982,
    genres: ["Pop", "R&B"],
    isFavorite: false,
    tags: [],
  },
  {
    id: "6",
    name: "The Velvet Underground & Nico",
    artist: "The Velvet Underground",
    image: "/placeholder.svg?height=300&width=300",
    year: 1967,
    genres: ["Art Rock", "Experimental"],
    isFavorite: false,
    tags: [],
  },
];

export const predefinedTags: Tag[] = [
  { id: "1", name: "Chill", color: "#3B82F6", isCustom: false },
  { id: "2", name: "Energetic", color: "#EF4444", isCustom: false },
  { id: "3", name: "Melancholic", color: "#6366F1", isCustom: false },
  { id: "4", name: "Uplifting", color: "#10B981", isCustom: false },
  { id: "5", name: "Experimental", color: "#F59E0B", isCustom: false },
  { id: "6", name: "Classic", color: "#8B5CF6", isCustom: false },
  { id: "7", name: "Modern", color: "#06B6D4", isCustom: false },
  { id: "8", name: "Nostalgic", color: "#EC4899", isCustom: false },
];
